import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import data from '../src/data/reference-data.json' with {type:'json'};
import contract from '../src/data/implementation-contract.json' with {type:'json'};
import {newCampaign,command,advance,advanceReported,formatResume,rates,cost,validate} from '../src/core/campaign.js';
import {save,load,decode,encode,SAVE_KEY,rememberView,rememberedView} from '../src/core/save.js';
import {project,inverse,camera} from '../src/client/projection.js';
const fresh=()=>newCampaign(contract,data,1000), build=(s,id,plotId,building,now=1000)=>command(s,{id,type:'BUILD',payload:{plotId,building}},now,data);
class Memory { values=new Map(); failAt=null; getItem(k){return this.values.get(k)??null;} setItem(k,v){if(k===this.failAt)throw new Error('Quota exceeded');this.values.set(k,v);}removeItem(k){this.values.delete(k);} }
test('frozen adoption: eight-age extensions and all twenty baseline tables',()=>{
  const oracle=JSON.parse(fs.readFileSync(new URL('../docs/plan/GAME-DATA-REFERENCE.json',import.meta.url),'utf8'));
  for(const[k,v]of Object.entries(oracle.originalTables)){const extension=oracle.productExtensions[k+'_ALL'];assert.deepEqual(data[k],extension?.value??v.value,k);}
  assert.equal(data.AGES.length,8);assert.equal(Object.keys(data.CLASSES).length,8);
});
test('sparse18sites, real stored starting ownership, zero built production',()=>{const s=fresh();assert.equal(s.plots.length,18);assert.equal(s.plots.filter(p=>p.level===0).length,17);assert.equal(s.walls.level,0);assert.deepEqual(s.resources,{food:250,wood:250,stone:160,gold:150});assert.equal(s.army[0].count,12);assert.deepEqual(rates(s),{food:0,wood:0,stone:0,gold:0});});
test('build replay spends once, conflicting transaction fails, prior state remains unchanged',()=>{const s=fresh(), next=build(s,'buy1','P01','lumber');assert.equal(next.resources.wood,225);assert.deepEqual(s,fresh());assert.deepEqual(build(next,'buy1','P01','lumber'),next);assert.throws(()=>build(next,'buy1','P02','farm'),/conflict/);});
test('unique facilities rejected before mutation, every producer instance independent',()=>{let s=build(fresh(),'b1','P01','barracks');const before=structuredClone(s);assert.throws(()=>build(s,'b2','P02','barracks'),/exists/);assert.deepEqual(s,before);s=build(s,'f1','P03','farm');s=build(s,'f2','P04','farm');s=advance(s,5000,data);assert.equal(rates(s).food,1.1);});
test('wrong Hall/Wall destination and unaffordable upgrade cannot spend',()=>{const s=fresh();for(const[site,type]of[['P01','townhall'],['townhall','farm'],['P01','walls']])assert.throws(()=>build(s,'bad',site,type));const poor=structuredClone(s);poor.resources.wood=0;assert.throws(()=>build(poor,'bad','P01','farm'),/resources/);assert.equal(poor.buildJobs.length,0);});
test('chronological offline construction produces only after completion, capped report cannot duplicate',()=>{let s=build(fresh(),'f1','P01','farm');s=advance(s,10000,data);assert.equal(s.resources.food,250+6*.55);const then=s.resources.food;s=advance(s,10000,data);assert.equal(s.resources.food,then);s=advance(s,10*3600000+10000,data);assert.equal(s.resources.food,then+8*3600*.55);});
test('resume report states the same credit once and records the screen outside the campaign',()=>{let s=build(fresh(),'f1','P01','farm');const first=advanceReported(s,10000,data);assert.equal(first.state.resources.food,250+6*.55);assert.equal(first.report.creditedMs,9000);assert.equal(first.report.capped,false);assert.equal(first.report.completed.length,1);assert.equal(first.report.income.food,6*.55);assert.match(formatResume(first.report),/0m 9s/);const repeat=advanceReported(first.state,10000,data);assert.equal(formatResume(repeat.report),'');assert.deepEqual(repeat.state,first.state);const capped=advanceReported(first.state,10*3600000+10000,data);assert.equal(capped.report.capped,true);assert.equal(capped.report.creditedMs,8*3600000);assert.equal(capped.report.income.food,8*3600*.55);assert.match(formatResume(capped.report),/age production cap/);const store=new Memory();save(store,first.state,data);rememberView(store,'adventure',['kingdom','adventure']);assert.equal(rememberedView(store,['kingdom','adventure']),'adventure');assert.equal(load(store,data).state.adventure,null);assert.throws(()=>rememberView(store,'portrait',['kingdom','adventure']),/Unknown screen/);});
test('backward clock does not award income or finish jobs',()=>{const s=build(fresh(),'f1','P01','farm');assert.deepEqual(advance(s,0,data),s);assert.throws(()=>build(s,'bad','P02','farm',0),/time/);});
test('initial tutorial budget builds four facilities and cost levelgrowth follows oracle',()=>{let s=fresh();for(const[i,type]of['lumber','farm','quarry','barracks'].entries())s=build(s,'t'+i,'P0'+(i+1),type);assert.equal(s.resources.wood,55);assert.equal(s.resources.stone,85);assert.deepEqual(cost(data,'townhall',1),{wood:105,stone:70});});
test('save distinguishes absent from corruption and offers last valid backup',()=>{const store=new Memory();assert.equal(load(store,data).status,'EMPTY');let s=fresh();save(store,s,data);s=build(s,'f1','P01','farm');save(store,s,data);store.values.set(SAVE_KEY,'broken');const result=load(store,data);assert.equal(result.status,'DAMAGED');assert.equal(result.state,null);assert.deepEqual(result.backup,fresh());});
test('quota failure during promotion leaves valid live and backup recoverable; stale writes rejected',()=>{const store=new Memory(), original=fresh();save(store,original,data);const next=build(original,'f1','P01','farm');store.failAt=SAVE_KEY;assert.throws(()=>save(store,next,data),/Quota/);assert.deepEqual(load(store,data).state,original);store.failAt=null;save(store,next,data);assert.throws(()=>save(store,original,data),/stale/);});
test('save checksum/domain rejects tampering, invalidresources, duplicateIDs and unsupported schemas',()=>{const s=fresh(),encoded=encode(s,data);assert.deepEqual(decode(encoded,data),s);assert.throws(()=>decode(encoded.replace('250','251'),data),/checksum/);for(const bad of [({...s,age:8}),({...s,resources:{...s.resources,gold:-1}}),({...s,schema:99})])assert.throws(()=>validate(bad,data));const bad=structuredClone(s);bad.army[1].id=bad.army[0].id;assert.throws(()=>validate(bad,data),/identity/);});
test('all world coordinates round-trip and one camera fit at all landscape targets',()=>{for(const g of Object.values(contract.geometry))for(const cell of [[0,0],[g.cols,g.rows],[g.cols/2,g.rows/2]]){const result=inverse(g.worldToSource,project(g.worldToSource,cell));assert.ok(Math.abs(result[0]-cell[0])<1e-9);assert.ok(Math.abs(result[1]-cell[1])<1e-9);for(const[w,h]of contract.viewports)assert.ok(camera(g.sourceSize,w,h).scale>0);}assert.throws(()=>inverse([1,1,1,1,0,0],[0,0]),/Noninvertible/);});
