import test from 'node:test';
import assert from 'node:assert/strict';
import data from '../src/data/reference-data.json' with { type: 'json' };
import contract from '../src/data/implementation-contract.json' with { type: 'json' };
import { newCampaign, command, validate } from '../src/core/campaign.js';
import { autoBattle, castSpell, deploy, startBattle, strike, wait } from '../src/core/battle.js';
import { MORALE_EFFECT, RANK_XP, addRankXp, creaturePool, dwellingCost, dwellingTerms, encounterVerdict, grantHeroXp, hostPower, makePack, previewStrike, rollLoot, towerStats, unitStats, wavePlan } from '../src/core/mechanics.js';
import { calcDamage } from '../src/core/mechanics.js';

const fresh = () => newCampaign(contract, data, 1000);
const fighter = (patch) => ({ side: 'e', count: 10, atk: 0, def: 0, dmin: 2, dmax: 2, uhp: 20, top: 20, spd: 5, rng: 0, shots: 0, ...patch });

test('derived unit and tower stats match the documented examples', () => {
  const stone = unitStats({ kind: 'role', type: 'melee', age: 0, rank: 0 }, data);
  assert.deepEqual([stone.atk, stone.def, stone.hp, stone.dmin, stone.dmax, stone.spd], [4, 5, 11, 2, 4, 5]);
  const future = unitStats({ kind: 'role', type: 'melee', age: 7, rank: 4 }, data);
  assert.deepEqual([future.atk, future.def, future.hp, future.dmin, future.dmax, future.spd], [22, 23, 70, 13, 25, 8]);
  const arrow = towerStats({ fam: 'arrow', tier: 7, rank: 4 }, data);
  assert.equal(arrow.dmg, 66.6);
  assert.ok(Math.abs(arrow.rng - 3.2) < 1e-9);
  assert.equal(arrow.hp, 1136);
  assert.equal(arrow.rate, 0.7);
  const ranked = unitStats({ kind: 'role', type: 'melee', age: 0, rank: 1 }, data);
  assert.equal(ranked.hp, 12);
  assert.throws(() => unitStats({ kind: 'role', type: 'melee', age: 8, rank: 0 }, data));
  assert.deepEqual(creaturePool(data, 0).every(id => data.CREATURES[id].t === 1), true);
  assert.ok(creaturePool(data, 7).every(id => data.CREATURES[id].t >= 3));
});

test('damage, preview and retaliation use the documented multipliers', () => {
  const hit = (patch, options) => calcDamage(fighter(patch), fighter({ side: 'e', def: patch.def ?? 0 }), options);
  assert.equal(hit({}).dmg, 20);
  assert.equal(hit({ atk: 60 }).dmg, 80);
  assert.equal(hit({ def: 28 }).dmg, 6);
  assert.equal(calcDamage(fighter({ rng: 6, shots: 2 }), fighter(), { ranged: true, adjacentEnemy: true }).dmg, 10);
  assert.equal(calcDamage(fighter({ atk: 5 }), fighter({ def: 5, defending: true }), {}).dmg, 16);
  assert.equal(calcDamage(fighter({ count: 61, dmin: 1, dmax: 1 }), fighter(), {}).dmg, 61);
  const attacker = fighter({ side: 'p', atk: 5, dmin: 2, dmax: 4 });
  const defender = fighter({ def: 5, count: 3, uhp: 10, top: 10 });
  const before = defender.count;
  const preview = previewStrike(attacker, defender, { hero: { atk: 0, def: 0, luck: 2, skills: {} } });
  assert.equal(defender.count, before);
  assert.ok(preview.dmin <= preview.dmax);
  const melee = fighter({ side: 'p', atk: 1, dmin: 1, dmax: 1, count: 1, uhp: 30, top: 30 });
  const reply = previewStrike(melee, fighter({ count: 2, uhp: 5, top: 5, dmin: 1, dmax: 1 }), {});
  assert.ok(reply.slainMax >= reply.slainMin);
});

test('hero experience, loot, dwellings and waves follow the addendum', () => {
  const state = fresh();
  state.hero.xp = 139;
  assert.equal(grantHeroXp(state, data, 1, 0), 1);
  assert.equal(state.hero.level, 2);
  assert.equal(state.hero.xp, 0);
  assert.equal(state.hero.points, 1);
  const jumped = fresh();
  assert.equal(grantHeroXp(jumped, data, 420, 0), 420);
  assert.equal(jumped.hero.level, 3);
  assert.equal(jumped.hero.xp, 0);
  assert.equal(jumped.hero.points, 2);
  assert.equal(jumped.hero.offers.length, 1);
  assert.equal(jumped.hero.offers[0].choices.length <= 2, true);
  const saved = structuredClone(jumped.hero.offers[0].choices);
  const declined = command(jumped, { id: 'decline', type: 'DECLINE_SKILL', payload: {} }, 1000, data);
  assert.deepEqual(declined.hero.offers[0].choices, saved);
  const credited = fresh();
  assert.equal(grantHeroXp(credited, data, 100, 2), 130);
  assert.equal(credited.hero.level, 1);
  const stack = { xp: 0, rank: 0 };
  addRankXp(stack, 60);
  assert.equal(stack.rank, 1);
  assert.deepEqual(RANK_XP, [0, 60, 180, 420, 900]);
  const generous = dwellingTerms({ generous: true });
  assert.deepEqual(generous, { count: 7, multiplier: 0.8 });
  assert.deepEqual(dwellingCost(data, 'wolf', 1), { food: 40, gold: 35 });
  assert.equal(dwellingCost(data, 'wolf', 0.8).food, 32);
  const wave = wavePlan(0, 0, 1);
  assert.equal(wave.total, 6);
  assert.equal(wave.hp, 26);
  assert.equal(wave.damage, 7);
  assert.equal(wave.speed, 0.85);
  assert.equal(wave.gap, 1);
  const later = wavePlan(4, 0, 1);
  assert.deepEqual(later.counts, { brute: 6, runner: 4, archer: 4, sapper: 2, shaman: 2 });
  assert.equal(later.total, 18);
  assert.equal(later.hp, 57);
  assert.ok(Math.abs(later.damage - 11.2) < 1e-9);
  assert.equal(later.speed, 0.97);
  assert.equal(later.gap, 0.8);
  assert.equal(encounterVerdict(1, 0), 'Deadly');
  assert.equal(encounterVerdict(0.7, 1), 'Easy');
  assert.equal(MORALE_EFFECT, 'PENDING_OWNER_DECISION');
  const host = hostPower(fresh().army, 3, 3);
  assert.ok(host > 0);
  const seeded = fresh();
  const first = makePack(seeded, data, 0, { row: 2 });
  const again = fresh();
  again.rngState = 123456789;
  assert.deepEqual(makePack(again, data, 0, { row: 2 }).stacks, first.stacks);
  let qualities = new Set();
  for (let rngState = 1; rngState < 50000 && qualities.size < 3; rngState++) {
    const probe = fresh();
    probe.rngState = rngState;
    const [drop] = rollLoot(probe, data, 0);
    if (drop?.kind === 'gear') qualities.add(drop.quality);
  }
  assert.deepEqual([...qualities].sort(), [0, 1, 2]);
});

test('legal combat corrections cover wait, resurrection, skirmish and the dead', () => {
  const stack = (id, side, speed) => ({ id, side, count: 2, atk: 1, def: 0, dmin: 1, dmax: 1, uhp: 80, top: 80, spd: speed, rng: 0, shots: 0, maxCount: 2 });
  const opened = startBattle({ id: 'b', rngState: 5, mana: 20, wisdom: 1, stacks: [stack('a', 'p', 6), stack('b', 'e', 1)] });
  const waiting = wait(opened, 'a');
  const answered = strike(waiting, 'b', 'a');
  assert.throws(() => wait(answered, 'a'), /Wait already used/);
  assert.equal(opened.queue[0], 'a');
  const healed = castSpell(startBattle({ id: 'heal', rngState: 1, mana: 20, wisdom: 1, stacks: [stack('a', 'p', 3), stack('b', 'e', 1)] }), { id: 'cure', lv: 1, mana: 5, type: 'heal' }, 'a', 1);
  assert.equal(healed.mana, 15);
  assert.throws(() => castSpell(opened, { id: 'resurrect', lv: 1, mana: 5, type: 'heal' }, 'missing', 1));
  const dead = stack('ghost', 'p', 1);
  dead.dead = true;
  dead.count = 0;
  assert.throws(() => deploy(opened, dead), /Dead stack/);
  const practice = autoBattle({ id: 'sk', practice: 'skirmish', rngState: 9, mana: 0, wisdom: 0, stacks: [stack('a', 'p', 5), stack('b', 'e', 1)] });
  assert.equal(practice.practice, 'skirmish');
  assert.equal(practice.status, 'RESOLVED');
  const campaign = fresh();
  const before = structuredClone(campaign);
  assert.equal(practice.outcome.practice, 'skirmish');
  assert.deepEqual(campaign.resources, before.resources);
  assert.throws(() => strike(opened, 'b', 'a'));
  const acted = strike(opened, 'a', 'b');
  assert.equal(acted.log[0].type, 'strike');
  assert.ok(validate(campaign, data));
});
