// Isolated local browser QA; no build or production writes. Only QA output files.
import {chromium} from 'file:///C:/Users/pupan/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import fs from 'node:fs/promises';import http from 'node:http';import path from 'node:path';import {fileURLToPath} from 'node:url';
const out=path.dirname(fileURLToPath(import.meta.url)),root=path.resolve(out,'../..');
const server=http.createServer(async(req,res)=>{try{const rel=decodeURIComponent(new URL(req.url,'http://localhost').pathname);const p=path.resolve(root,'.'+(rel==='/'?'/index.html':rel));if(path.relative(root,p).startsWith('..'))throw Error('outside');const types={'.html':'text/html','.js':'text/javascript','.json':'application/json','.css':'text/css','.png':'image/png','.jpg':'image/jpeg','.webp':'image/webp'};const body=await fs.readFile(p);res.writeHead(200,{'Content-Type':types[path.extname(p)]??'application/octet-stream'});res.end(body);}catch{res.writeHead(404);res.end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const contexts=[];const errors=[];const rows=[];
async function fresh(viewport={width:1280,height:720},init=null){const c=await browser.newContext({viewport});contexts.push(c);if(init)await c.addInitScript(init);const p=await c.newPage();p.on('pageerror',e=>errors.push(String(e)));await p.goto(url);await p.waitForFunction(()=>typeof window.rebornSnapshot==='function');return p;}
async function openPanel(p){if(await p.locator('#context').getAttribute('aria-expanded')!=='true')await p.locator('#context').click();}
async function survey(p){return p.evaluate(()=>{const r=e=>{const q=e.getBoundingClientRect();return{x:q.x,y:q.y,width:q.width,height:q.height,right:q.right,bottom:q.bottom};};const stage=r(document.querySelector('#stage')),panel=document.querySelector('#panel').classList.contains('open')?r(document.querySelector('#panel')):null;return{stage,panel,frame:getComputedStyle(document.querySelector('#frame')).transform,hall:r(document.querySelector('#world image')),sites:[...document.querySelectorAll('.plot')].map(e=>{const t=r(e.querySelector('rect'));return{id:e.getAttribute('aria-label').split(':')[0],target:t,inside:t.x>=stage.x-.01&&t.y>=stage.y-.01&&t.right<=stage.right+.01&&t.bottom<=stage.bottom+.01,uncovered:!panel||t.right<=panel.x+.01,min48:t.width>=47.99&&t.height>=47.99};})};});}
try{
 for(const [width,height] of [[825,375],[933,424],[1180,820],[1280,720]]){
  const p=await fresh({width,height});const closed=await survey(p);await openPanel(p);const opened=await survey(p);if(width===825)await p.screenshot({path:path.join(out,`kingdom-panel-${width}x${height}.png`)});
  const picks=[];for(const id of opened.sites.map(s=>s.id)){const s=(await survey(p)).sites.find(s=>s.id===id);await p.mouse.click(s.target.x+s.target.width/2,s.target.y+s.target.height/2);picks.push({id,picked:await p.evaluate(()=>window.rebornPick?.site??null)});}rows.push({viewport:[width,height],closed,opened,picks});await p.context().close();
 }
 const p=await fresh();await p.getByRole('button',{name:'Home',exact:true}).click();await openPanel(p);await openPanel(p);await p.getByRole('button',{name:'Save slot 1',exact:true}).click();const old=await p.evaluate(()=>({state:window.rebornSnapshot(),live:localStorage.getItem('aod-reborn-v1')}));
 await p.getByRole('button',{name:'Story',exact:true}).click();await p.getByRole('button',{name:'Varek Iron-Eye',exact:true}).click();const progressed=await p.evaluate(()=>({state:window.rebornSnapshot(),live:localStorage.getItem('aod-reborn-v1')}));await p.screenshot({path:path.join(out,'story.png')});
 await p.getByRole('button',{name:'Home',exact:true}).click();await openPanel(p);await p.getByRole('button',{name:'Load slot 1',exact:true}).click();const slot=await p.evaluate(()=>({state:window.rebornSnapshot(),live:localStorage.getItem('aod-reborn-v1'),status:document.querySelector('#status').textContent,message:document.querySelector('#message').textContent}));await p.reload();await p.waitForFunction(()=>typeof window.rebornSnapshot==='function');const slotReload=await p.evaluate(()=>window.rebornSnapshot());
 await p.getByRole('button',{name:'Home',exact:true}).click();await openPanel(p);p.once('dialog',d=>d.accept());await p.getByRole('button',{name:'New campaign',exact:true}).click();const newCampaign=await p.evaluate(()=>({state:window.rebornSnapshot(),live:localStorage.getItem('aod-reborn-v1'),status:document.querySelector('#status').textContent,message:document.querySelector('#message').textContent}));await p.reload();await p.waitForFunction(()=>typeof window.rebornSnapshot==='function');const newReload=await p.evaluate(()=>window.rebornSnapshot());
 const importFile=path.join(out,'valid-earlier-save.json');await fs.writeFile(importFile,old.live);await p.getByRole('button',{name:'Home',exact:true}).click();await openPanel(p);await p.locator('#import-file').setInputFiles(importFile);await p.waitForTimeout(100);const imported=await p.evaluate(()=>({state:window.rebornSnapshot(),live:localStorage.getItem('aod-reborn-v1'),status:document.querySelector('#status').textContent,message:document.querySelector('#message').textContent}));await p.reload();await p.waitForFunction(()=>typeof window.rebornSnapshot==='function');const importReload=await p.evaluate(()=>window.rebornSnapshot());
 const recovery=await fresh({width:1280,height:720},()=>{if(!sessionStorage.getItem('qa-init')){sessionStorage.setItem('qa-init','1');localStorage.setItem('aod-reborn-v1','broken-save');}});await openPanel(recovery);const corruptHome={buttons:await recovery.locator('#choices button').allTextContents(),message:await recovery.locator('#message').textContent()};await recovery.screenshot({path:path.join(out,'damaged-home.png')});
 await recovery.evaluate(bytes=>{localStorage.setItem('aod-reborn-v1-backup',bytes);},progressed.live);await recovery.reload();await recovery.waitForFunction(()=>typeof window.rebornSnapshot==='function');await openPanel(recovery);await recovery.getByRole('button',{name:'Restore valid backup',exact:true}).click();const restored=await recovery.evaluate(()=>({state:window.rebornSnapshot(),live:localStorage.getItem('aod-reborn-v1'),damaged:localStorage.getItem('aod-reborn-v1-damaged'),backup:localStorage.getItem('aod-reborn-v1-backup')}));
 for(const name of ['Hero','Adventure']){await p.getByRole('button',{name,exact:true}).click();await p.screenshot({path:path.join(out,name.toLowerCase()+'.png')});}
 await p.getByRole('button',{name:'War',exact:true}).click();await openPanel(p);await p.getByRole('button',{name:'Skirmish',exact:true}).click();await p.screenshot({path:path.join(out,'tactical.png')});
 const d=await fresh();await d.getByRole('button',{name:'War',exact:true}).click();await openPanel(d);await d.getByRole('button',{name:'Campaign Siege',exact:true}).click();await d.waitForTimeout(1200);await d.screenshot({path:path.join(out,'defense.png')});await d.evaluate(()=>window.rebornBackground(true));const defenseBefore=await d.evaluate(()=>window.rebornSnapshot().defense.time);await d.waitForTimeout(700);const defenseAfter=await d.evaluate(()=>window.rebornSnapshot().defense.time);
 const a=await fresh();await a.evaluate(()=>{const Native=window.AudioContext;window.qaAudioStarts=0;window.AudioContext=class extends Native{createOscillator(){const osc=super.createOscillator(),start=osc.start.bind(osc);osc.start=(...args)=>{window.qaAudioStarts++;return start(...args);};return osc;}};});await a.getByRole('button',{name:'Settings',exact:true}).click();await openPanel(a);await a.getByRole('button',{name:'Arm local audio',exact:true}).click();await a.waitForTimeout(500);await a.evaluate(()=>window.rebornBackground(true));const audioBefore=await a.evaluate(()=>window.qaAudioStarts);await a.waitForTimeout(950);const audioAfter=await a.evaluate(()=>window.qaAudioStarts);await a.evaluate(()=>window.rebornBackground(false));await a.waitForTimeout(600);const audioResumed=await a.evaluate(()=>window.qaAudioStarts);
 const result={at:new Date().toISOString(),errors,rows,saveUI:{oldRevision:old.state.revision,progressedRevision:progressed.state.revision,slot,slotReload,newCampaign,newReload,imported,importReload,corruptHome,restored},background:{defenseBefore,defenseAfter,audioBefore,audioAfter,audioResumed},scope:'Fresh root source, actual controls. Isolated localStorage. Save export fixture contains only synthetic local test campaign. No APK/device/owner acceptance.'};await fs.writeFile(path.join(out,'browser.json'),JSON.stringify(result,null,2));
 console.log(JSON.stringify({errors,geometry:rows.map(r=>({viewport:r.viewport,closedClipped:r.closed.sites.filter(s=>!s.inside).map(s=>s.id),openedClipped:r.opened.sites.filter(s=>!s.inside||!s.uncovered).map(s=>s.id),closedMin:Math.min(...r.closed.sites.map(s=>s.target.width)),openedMin:Math.min(...r.opened.sites.map(s=>s.target.width)),pickFailed:r.picks.filter(s=>s.id!==s.picked)})),save:{old:old.state.revision,progressed:progressed.state.revision,slotMemory:slot.state.revision,slotReload:slotReload.revision,newMemory:newCampaign.state.revision,newReload:newReload.revision,importMemory:imported.state.revision,importReload:importReload.revision,importMessage:imported.message,corruptHome},background:result.background},null,2));
}finally{for(const c of contexts)await c.close().catch(()=>{});await browser.close();await new Promise(r=>server.close(r));}
