// Isolated local browser QA; no build or production writes. Only QA output files.
import {chromium} from 'file:///C:/Users/pupan/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import fs from 'node:fs/promises';import http from 'node:http';import path from 'node:path';import {fileURLToPath} from 'node:url';
const out=path.dirname(fileURLToPath(import.meta.url)),root=path.resolve(out,'../..');
const server=http.createServer(async(req,res)=>{try{const rel=decodeURIComponent(new URL(req.url,'http://localhost').pathname);const p=path.resolve(root,'.'+(rel==='/'?'/index.html':rel));if(path.relative(root,p).startsWith('..'))throw Error('outside');const types={'.html':'text/html','.js':'text/javascript','.json':'application/json','.css':'text/css','.png':'image/png','.jpg':'image/jpeg','.webp':'image/webp'};const body=await fs.readFile(p);res.writeHead(200,{'Content-Type':types[path.extname(p)]??'application/octet-stream'});res.end(body);}catch{res.writeHead(404);res.end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const contexts=[];const errors=[];const rows=[];
async function fresh(viewport={width:1280,height:720},init=null){const c=await browser.newContext({viewport});contexts.push(c);if(init)await c.addInitScript(init);const p=await c.newPage();p.on('pageerror',e=>errors.push(String(e)));await p.goto(url);await p.waitForFunction(()=>typeof window.rebornSnapshot==='function');return p;}
async function openPanel(p){if(await p.locator('#context').getAttribute('aria-expanded')!=='true')await p.locator('#context').click();}
async function survey(p){return p.evaluate(()=>{const r=e=>{const q=e.getBoundingClientRect();return{x:q.x,y:q.y,width:q.width,height:q.height,right:q.right,bottom:q.bottom};};const stage=r(document.querySelector('#stage')),panel=document.querySelector('#panel').classList.contains('open')?r(document.querySelector('#panel')):null;return{stage,panel,frame:getComputedStyle(document.querySelector('#frame')).transform,hall:r(document.querySelector('#world image')),sites:[...document.querySelectorAll('.plot')].map(e=>{const t=r(e.querySelector('rect'));return{id:e.getAttribute('aria-label').split(':')[0],target:t,inside:t.x>=stage.x-.01&&t.y>=stage.y-.01&&t.right<=stage.right+.01&&t.bottom<=stage.bottom+.01,uncovered:!panel||t.right<=panel.x+.01,min48:t.width>=47.99&&t.height>=47.99};})};});}
try{
 const p=await fresh();const bytes=await p.evaluate(async()=>{const [{newCampaign},data,contract,{encode}]=await Promise.all([import('/src/core/campaign.js'),import('/src/data/reference-data.json',{with:{type:'json'}}),import('/src/data/implementation-contract.json',{with:{type:'json'}}),import('/src/core/save.js')]);const s=newCampaign(contract.default,data.default,Date.now());s.army[0]={id:'qa-wolf',kind:'creature',type:'wolf',age:0,count:5,rank:0,xp:0};return encode(s,data.default);});
 const f=await fresh({width:1280,height:720},{content:`localStorage.setItem('aod-reborn-v1',${JSON.stringify(bytes)});`});await openPanel(f);const before=await f.evaluate(()=>window.rebornSnapshot());const e0=errors.length;await f.getByRole('button',{name:'Army',exact:true}).click();await f.waitForTimeout(100);await f.screenshot({path:path.join(out,'army-creature-fixture.png')});const result={at:new Date().toISOString(),before,errors:errors.slice(e0),buttons:await f.locator('#choices button').allTextContents(),scope:'New context initialized before first app load, validated synthetic wolf save; no natural recruitment claim.'};await fs.writeFile(path.join(out,'creature.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({army:before.army,errors:result.errors,buttons:result.buttons},null,2));
}finally{for(const c of contexts)await c.close().catch(()=>{});await browser.close();await new Promise(r=>server.close(r));}
