"""Write owner handoff text and documentation pointers; no execution or production edits."""
from pathlib import Path
import json
ROOT = Path(__file__).resolve().parents[2]
PLAN = ROOT / 'docs/plan'

code = '''REPLACEMENT CODE / ART-PROCESSING AI — OWNER HANDOFF, 3 OCTOBER 2026

Work in C:/dev/ages-of-dominion-reborn. You replace the code AI whose usage ended. Finish the independently authored game against the complete plan, process existing art, then commit/push to https://github.com/arghaG123/ages-of-dominion-reborn AFTER your next task completes. This is authorization for the owner-selected executor; the planner chat remains verifier-only. No paid image calls, executor messaging/delegation or resumption of stopped physical-device testing. Routine authorized implementation, processing, tests and builds need no repeated permission.

READ FIRST
Read AGENTS.md, START-HERE.md, CURRENT-STATUS.md, DECISIONS.md, docs/SESSION-HANDOFF.md, docs/BUILD-PROGRESS.md, docs/PLANNER-VERIFIER-HANDOFF.md and docs/plan/README.md. Current evidence: WHOLE-IMPLEMENTATION-PLANNER-AUDIT-2026-10-03.md and qa/whole-implementation-audit-20261003/. Read FULL-IMPLEMENTATION-SPEC.md, MASTER-PLAN.md, REQUIREMENTS-TRACEABILITY.md, SOURCE-EQUATIONS-ADDENDUM-2026-10-03.md, ASSET-ACCEPTANCE-CLARIFICATION-2026-10-03.md, latest candidate/recovery audits, approved landscape mocks and their recorded defects, implementation contract, frozen game data, installed environment, INTERACTIVE-HIGH-RES-QUEUE-2026-10-03.json and GIT-ASSET-STORAGE-PLAN-2026-10-03.md. Refresh actual file state before relying on historical status.

TASK BOUNDARIES
Complete all eight ages, Kingdom, Adventure, Tactical, Defense, eight classes, six functional equipment slots, connected campaign, five War options and supporting systems. A demo slice never replaces the full scope. Old C:/dev/ages-of-dominion and C:/dev/aod-art-src are read-only requirement/art/config references; do not copy/import old gameplay/client/core code. Preserve recorded permanent application ID and separate preview ID. Fully offline runtime: no cloud/account/CDN/store publishing, INTERNET/VIBRATE or other declared/granted permissions. Use installed tools. APK builds/static inspection are authorized; installation, physical device tests and 60fps acceptance remain stopped/unverified without renewed owner authorization.
Work in reviewable checkpoints and persist until authorized work is complete. Do not call placeholder buttons/messages/diagrams a complete game or award owner acceptance yourself. If a genuine rule/review/storage blocker remains, prepare a concrete reviewable result, identify the exact missing decision, and continue independent work. Positive morale remains a pending owner decision in the source-equations addendum; do not invent its effect to close a checklist. Keep technical, asset, scene, game, native and owner acceptance separate.

1. REPRODUCE AND REPAIR THE FRESH FAILURES
The current 41 tests pass, but core-probes.json/browser-checks.json reproduce these failures:
- Dwelling claim with capacity 2 and two existing stacks creates a third, spends 35 gold and validates. Enforce capacity/site/offer/tier eligibility before charging; rejected commands leave state unchanged. Saved offers must not reroll on cancel/reload.
- Tactical saves accept negative mana/damage, zero maxCount, empty active queue, RNG above 32 bits, false resolved victory with both sides alive, and blocked-water flyer destinations. Validate numeric bounds, enums, phase/queue/turn/effects/positions/outcomes, encounter/entity identity and campaign linkage, including pending results. Flight may cross obstacles but ends legally. Reject corrupt settlements without rewards/restocking; preserve valid real casualties/survivors and exactly-once settlement.
- Legal melee approach is advertised but client sends forceMelee without approach and receives “Not adjacent.” Preview/select/send the complete legal approach+attack transaction. Keep core remote-hit rejection.
- Home overwrites the remembered scene; Continue loops to Home. Preserve last eligible scene and battle/result destination.
- Booting with a damaged save, then New campaign, leaves the clock stopped. New/restore/recovery must install exactly one lifecycle timer with ordered saves and exactly-once away production/construction credit. Test backup restore, repeated new campaign, navigation and reload.
Add meaningful negative/regression tests and browser interaction evidence. Retain the existing repairs for movement refill, guard bypass and illegal remote melee; these old failures are resolved within current test coverage.

2. RECONCILE AND PROCESS EXISTING ART
Current production01–17 is locally collected: 510 originals, 504 IDs, 510 hashes; saved jobs all SUCCEEDED. Decode/source/prompt associations pass. Consumer has 510 fresh rows, 85 selected, zero runtimeApproved/ownerAccepted; scene FAIL. Baseline480 has 431 literal matches plus49 local alias candidates, NOT49 missing purchases. Inspect qa/.../alias-candidates.json and actual content before adopting aliases. Preserve immutable originals/raw responses/requests/provenance/rejected versions; do not overwrite sources.
Review batch17 attacker-AGE-heavy as candidates for canonical troop-AGE-heavy: corrected Bronze chariot, Iron elephant, Gunpowder cannon and Industrial/Modern/Future heavy forms. Do not replace the five siege attacker roles with these. Iron Splash is a non-cannon throwing mechanism now, but exact Onager form is unverified. Reuse earlier correct Stone flint weapon instead of production03 terrain. Ancient Warlock portrait, motor harness and isolated Cave Bear have content failures. Spell-sheet labels require useful-part review. These issues do not authorize extra purchases.
Keep five bounded UI passes: Food/Wood/Stone18px, Goldv3 and Offense36/64px. Hallv3 still has a native pink warning requiring measured matte/subject preservation. Generated128 gear IDs are selected variants, not8*4*6. Rival art names are appearance candidates only: retain frozen game names Varek Iron-Eye, Malakor the Flayed, Thalric Ash-Bane, Bran the Relentless, Karn Blood-Tide, Soren the Unforgiving, with explicit reviewed appearance-slot mappings.
Create clean optimized derivatives/atlases with source hash, native dimensions, crop/matte/part extraction transforms, measured ground pivots/footprints/roof envelope/facing/light/depth. Inspect silhouettes at native and actual display size; inspect rigs/contact shadows at clip extremes. Discovery, filename and decode are not art approval. Keep failed/recoverable/unverified files and history. Integrate validated1K now through manifests so later high-resolution substitutions do not hardcode dimensions.

3. REPAIR KINGDOM AND EXPORT READY IMAGE GUIDES
Live terrain still bakes mutable plot rectangles/huts/logs; Hallscale .1312; buildings are polygons/numerals. Candidatev2 .34 uniform envelope fits the roof, but inferred rear corners/rectangular terrace,12 blocking door occlusions,9 acceptable overlaps and tabletP11 panel coverage remain. Reviewchrome92px differs from runtime112px. v2/v5 guides remain NOT_OWNER_ACCEPTED. Batch14 compositionv4 is attractive reference, but river/crossings/site layout and Hall differ; it is not approved playable terrain.
Create a versioned coordinated proposal: actual measured Hall threshold/base polygon/entrance/full roof, physical civic terrace,17 legal clearings, mature silhouettes/door approaches/roads, lower gate/right river/crossing and same homeland across eight ages. One worldToSource and one sourceToViewport transform must serve terrain/actors/selection/routes/inverse picking. Logical source1376x768; follow contract anchors/continuous road coordinates. Never shrink/warp Hall or move only overlays to hide collisions. Review geometry changes explicitly; no silent adoption of v2/v5.
Demonstrate sparse Day1 and dense mature states, circulation, occupied/empty/construction variants and full age conversion at825x375,933x424,1180x820,1280x720, panels closed/open and safe areas. Current phone world width57–60% fails>=80% unoccluded overview. Use actual sprite silhouettes and physical approaches, not only rectangles. Stone has no medieval church/castle kit; Future transforms the same homeland without incompatible rural carryover.
Export a local per-ID image guide pack: logical/native geometry JSON, overlay guide, overlay-free base, masks/immutable landmarks, verified source hashes, intended camera/light/aspect, comparisons and explicit spatial tolerance/acceptance. Record review status honestly; do not self-award owner approval. Missing required geometry/acceptance blocks that scene's image request, not unrelated ready IDs or independent code work. Save handoff files for the owner; no executor messages.

4. COMPLETE THE WORLD ENGINES AND SUPPORTING SYSTEMS
- Kingdom: all building functions/sprites, production/construction/workers/perimeters, Hall/age transition and complete eight-age ground/path/field/transport/building conversion. No screenshot hotspots as dynamic scenery.
- Adventure: natural generated biomes, registered sites/pickups/guards/dwellings/encounters and mounted rigs; legal path preview/confirm, committed travel, common pan/zoom/picking, persistent movement/occupancy/rival/story and battle transitions. No navigation reward bypass or movement refill.
- Tactical: legal deployment and full specified roster capacity up to6 stacks, autonomous opponent turns, queue/range/damage/spell/target previews, move/melee/ranged/flying/defend/wait/Auto/retreat, seeded reload/resume. Three-to-seven cosmetic figures per stack, rear figure losses and persistent entity IDs; measured facing/depth/contact and authored rig clips. Player must not manually drive enemies. Results/casualties/loot/XP/quests reconcile once against source IDs.
- Defense: pure fixed1/60 step with interpolation/bounded accumulator, pause/background no hidden attacks,2x consistent simulation/clips. Visible spawn/roles/lane/pads/interception, distinct projectile/splash/control/aura towers, legal once-per-session army/hero deployment with ZERO fee, persistent treasury Buy/Retrofit, wave preview/HP/enemy/ability states and adopted settlement. No invented purse/kill income. Resolve the scenario/formula ledger before completion.
- Five War options: Campaign Siege, Tactical Duel, Endless, Skirmish and offline reproducible Challenge with defined seed/results/losses/rewards. Skirmish isolates campaign XP/mana/gold/story/casualties/early-call income. No dead buttons.
- Hero/Inventory/Forge: visible class/era/kit, six unique functional slots helm/weapon/offhand/armor/boots/accessory, craft/loot/equip/unequip/compare, compatibility and real stat effects. Old gear stays visibly old until replaced; no free stats on age change. Real upgrade points/skill offers and eligible spellbook targets/costs.
- Army/Market/Codex: three army roles through eight ages, neutrals, quantities/ranks/stats/capacity/cost, legal reinforce/split/merge only under defined rules. Bronze Market unlock/exact transactions/insufficient states. Armory>=1 before Forge quality/cost calculation.
- Story/quests/tutorial/support: seven frozen chapters plus Future “The Valley We Keep”, six quests, eight milestones, saved frozen rival/branch and once-only claims. Tutorial advances only correct real commands. Actual authorized local Music/SFX sources with independent buses, reduced motion retaining command timing, usable help/credits/privacy. Buses/beep alone are not music. No permission-requiring haptics or runtime remote media.

5. VISUAL ACCEPTANCE AND DELIVERY
Use approved landscape mocks as appearance anchors with recorded synchronization/era/name corrections; never adopt invented stats/text/mechanics. Natural inhabited scenes, readable icons, slate/stone/brass chrome. No diagrammatic final worlds or empty support stages. Compact edge HUD,48px legal targets,safe areas, keyboard/focus, real default/pressed/disabled/loading/empty/error/success states. Resource rail18px icon/28px exception only Kingdom/Adventure; none in Tactical/Defense/results. Portrait retains state and shows accessible rotate message.
Articulated actors/mounts need true idle/walk/work/attack/hit/death clips, ground contact/facing/depth/shadows; wobble is not gait. One transform per scene. Save actual side-by-side pixels for every surface/all8ages/representative biomes/classes/battles, four viewport sizes and dense/open/panel states. No-overflow/decode/tests are limited technical evidence. Record FAIL/UNVERIFIED and actual owner review separately.

6. VERIFY AND PACKAGE
Run tests for repairs and connected journeys: build/recruit/gear/travel/Tactical/Defense/settlement/age/story/save/restore. Include negative saves, duplicate settlement, lifecycle clock and Skirmish isolation. Refresh benchmark/discovery against510 sources and actual consumers; saved627PASS/1budgetFAIL/11manualUNVERIFIED covers480 and is stale. Preserve historical reports.
Repair consumer budget accounting against producer's evidence-bounded57.225USD and retained119USD historical holds. Never erase holds, change producer locks/billing or treat unknown invoice aszero. Keep aim60/hard80/protected15.
Build self-contained browser output and verify referenced local art/font/audio hashes/no network. Existing16-source/23-asset dist closure passes only for that snapshot. Build previewAPK when native packaging is ready; statically verify application ID/landscape/zero permissions and asset closure. No installation/device run while stopped. Build/native runtime/performance acceptance remain separate.
Update CURRENT-STATUS, SESSION-HANDOFF, BUILD-PROGRESS, traceability and evidence index at checkpoints/handoff. Do not stop with a “helpful enough” demo. Real unresolved gates require precise evidence and a concrete remaining-work handoff.

7. AFTER TASK COMPLETION: PRESERVE, COMMIT, PUSH
Owner destination: https://github.com/arghaG123/ages-of-dominion-reborn. Commit/push AFTER next task completes and checks, not before. Localcodex/rebuild currently has no commits/tracked files/remote; inspect fresh state. Entire assets/ stays OUTSIDE Git, including production/delivery; no LFS/raw payload/secret upload. Exclusion does not authorize move/delete.
Before ignore/staging:
1) Classify files explicitly and prepare pinned hash/size/provenance restore manifest. Include originals/raw requests/responses/derivatives/guides/rejected versions and unique QA/preview/reference evidence. No blanket QA/preview exclusion or history disposal. Sanitized catalogs retain provenance but no credentials/tokens/private keys.
2) Preserve external archive AND independent durable second copy; verify counts/bytes/SHA256 and clean restore to expected paths, including offline packaging. A same-disk duplicate or provider bucket is not automatically proven durable complete backup. Keep local originals untouched.
3) Only Git destination is supplied. Archive/backup destinations/access/cost scope remain missing unless current configuration proves them. Finish reviewable manifest/storage proposal first, then ask only for truly missing destinations. Do not invent accounts/enable paid storage/expose secrets. If this gate fails, report Git blocked while preserving completed code/evidence; no repeated blanket push confirmation is needed.
4) After verified storage/restore, apply /assets/ ignore and other explicitly approved classification. Commit sanitized restore manifest/recipe. Verify git check-ignore/git ls-files and no asset leakage through embedded JSON/base64 or preview copies.
5) Inspect remote refs/history using existing auth. Reconcile existing content non-destructively; never force push/overwrite unrelated history. Configure supplied origin locally afterward. Use established Git identity; ask only if missing, never invent/change global identity.
6) Stage explicit approved paths; inspect staged diff/stat/large files/secrets/reference closure, never git add . . Create meaningful commit, push codex/rebuild unless owner/verified remote convention specifies another branch, verify remote commit SHA. No PR required. Report branch/commit/backup/restore evidence and remaining acceptance gates.

DELIVER
Concrete changes; reproduced/fixed defects; full-scope matrix; current art consumers/image guide pack; fresh engine/pixel/package evidence; all remaining limitations/owner decisions; then verified preservation and commit/push result if gates pass. No paid image execution. Image AI owns32 individual4K first and73 later proposed2K, not unlimited replacement art.
'''

image = '''IMAGE GENERATION AI — OWNER HANDOFF, 3 OCTOBER 2026

You are the owner-selected image executor in C:/dev/ages-of-dominion-reborn. Owner requests32 INDIVIDUAL native4K images FIRST, then later73 native2K images in divided groups. This specific individual upgrade phase supersedes old batch-only/30-position rules. No batch18+,32-request provider batch, pilot/test image, filler, supplemental call or unrelated replacement. Code processing belongs to the separate owner-selected AI. No executor messaging/delegation or game code edits.

READ FIRST / CURRENT STATE
Read AGENTS.md, CURRENT-STATUS.md, DECISIONS.md, current handoff, WHOLE-IMPLEMENTATION-PLANNER-AUDIT-2026-10-03.md, FULL-IMPLEMENTATION-SPEC.md, source-equation/asset-acceptance/candidate corrections, installed environment, budget/storage plans and INTERACTIVE-HIGH-RES-QUEUE-2026-10-03.json. Inspect actual per-ID source/prompt/guide before calling.
Production01–17 are locally collected:30 outputs each,510 originals,504 IDs,510 hashes. Source/prompt associations pass. Saved provider records all SUCCEEDED; batch17 lock TERMINAL_COLLECTED, last checked/collected2026-10-03T15:25:06UTC. This is not a fresh provider listing. Baseline480 has431 literal matches and49 local alias candidates; no49-image purchase backlog established. Consumer510 fresh/85 selected/zero runtimeApproved or ownerAccepted; scene FAIL. Preserve all originals/raw responses/provenance/rejected versions; no move/delete/overwrite.

MODEL / READINESS / LOCK
Use supplied Vertex project project-eaa4c1cc-8f19-4d24-9e6, requested account arghawork3@gmail.com, existing authorized bucket, current official gemini-3.1-flash-image global individual generateContent image/edit API, candidateCount1, imageSize4K first. Later activated groups use2K. Request-specific project/account; no global CLI/billing/IAM/account changes, other project/provider/API-key fallback. Verify current official capabilities/tariff/parameter support before paid calls, without test generations.
Reconcile fully paginated global/US-Central1 operation listings plus local/cloud locks. ONE active/unknown operation across all sessions in this project, including individual calls. Old billing-disabled project remains untouched/unknown under owner project exception. Saved terminal files alone do not prove live zero operations. Use shared local mutex and conditional cloud lock/write-ahead reservation before each POST; do not clear another executor's lock.
Inspect usable existing native high-res outputs before buying; reuse accepted output. Current inspected originals are1K. Resolve aliases by content, select source hashes and required ready reviewed guide. Queue preferredSource/guide are currently null/UNVERIFIED, not ready. Code AI exports geometry/base/masks/camera locally. Missing required geometry/acceptance blocks only that scene's request; continue unrelated ready selected IDs with a recorded deferral. No silent adoption of Kingdomv2/v5 guide or compositionv4 as owner-approved playable layout.

BUDGET BEFORE PAID CALLS
AimUS$60, HARDUS$80, protectedUS$15 reserve never spent. Independently summed510 records:985482 input/574764 output tokens. Producer evidence-bound protected exposure57.225USD includes conservative standard image-priced output34.978581, rounded15% overhead, historicalmock2 and reserve15. Invoice billedTotal remains UNKNOWN. Historical17*$6 holds+mock/reserve=119USD remain preserved; consumer budget still uses raw sum. Reconcile schema/history/all liabilities from evidence; never erase holds or assume unknown invoices arezero.
Current official standard rates: input$0.50/M tokens,image output$60/M,text$3/M. Native4K2520 image tokens=$0.1512 each;2K1680=$0.1008.32 first image outputs=$4.8384,73 later=$7.3584; inputs/text/storage/tax extra. First32 exceed60 aim under expected cost. No increased spending authority.
Queue proposes maxOutputTokens4096 for4K,2048 for later2K,input<=4000 tokens/call,15% overhead. Count full image+text input; at most3 reference images at1120 tokens each leaves640 text tokens under this proposal. Confirm actual provider caps/accounting. Reserve ALL capped output at image price plus bounded input/overhead. Conditional whole105 protected ceiling76.826244USD leaves only~3.17 below80; this is not an invoice/adopted reservation. If actual caps/liabilities/tax/overhead cannot bound exposure under80 with15 protected, stop/report the precise gap. No raising caps, spending reserve or retrying incomplete capped output. No image calls to investigate prices.
Official sources:
https://cloud.google.com/gemini-enterprise-agent-platform/generative-ai/pricing
https://docs.cloud.google.com/gemini-enterprise-agent-platform/models/gemini/3-1-flash-image
https://docs.cloud.google.com/gemini-enterprise-agent-platform/models/capabilities/gemini-edit-images

ONE AUTHORIZED OUTPUT ATTEMPT PER ID
Persist attempt manifest BEFORE POST: canonicalID/phase/order, immutable source/guide hashes, exact prompt/hash, model/project/region,size/aspect,candidateCount1, token/price caps, reservation/attemptID and mutex state. Sequential individual requests; review/save each result before next ready ID. No overlap with active/unknown batches/calls in any session. No automatic POST retry, regeneration, duplicate or32-plus-pilot. Rejected output uses its authorized attempt; report it for owner decision, not an automatic second purchase.
Timeout/ambiguous connection/nonterminal response =>UNKNOWN with durable lock/liability. Never clear because old, resend or switch provider. Reconcile only from provider evidence. FIRST quota/429/billing-disabled/exhaustion stops provider work: no fallback or repeated probing. Save sanitized error/attempt state. Terminal is not art acceptance. Old next-batch-before-collection rule does not authorize new batches here.

FIRST32 TERRAIN PROMPT CONTRACT
Use native image editing with reviewed base/reference/geometry guide where supported. Specify exact period/biome, camera/projection/light, immutable landmarks, clearings/routes/river/crossings/lane/pads and margins from the ready guide. Preserve geometry within the explicit tolerance adopted in the guide pack. Logical source1376x768,16:9 direction. Decode actual native width/height and check aspect/uniform logical mapping. Do not guess3840x2160, label upscale as native4K, or warp terrain/overlay independently.
Natural realistic/semi-realistic inhabited landscape, readable traversable ground/contact/depth and clear overlay space. BACKGROUND ONLY: no baked mutable Hall/buildings/towers/walls/units/heroes/pickups/HUD/labels/plot rectangles/grid/guide colors. Set dressing avoids registered footprints/door approaches/routes. Guide is geometry reference, not content to paint. Code AI provides separate Hall/buildings/perimeters/actors. Do not substitute full compositionv4 for bare terrain.
- Kingdom8 ages: same upper civic terrace/valley ridge/lower gate/right river/crossing,17 legal clearings/road approaches; period-correct ground/path/landscape support. Stone has no medieval church/castle kit. Future retains homeland without incompatible rural carryover. Follow frozen identities, no invented building types.
- Adventure8: forest default plus plains,hills,swamp,desert,snow,waste,ruins; preserve playable map/site footprints/routes/movement edges and common camera. No baked heroes/sites/pickups/guards.
- Tactical8: same biome list, registered board/deployment/river/obstacles/ground under common projection; no painted units/grid/HUD/sky targets. Hard obstacles agree with logical legality.
- Defense8: same biome list, visible entry/gate/winding lane/pads/deployment areas; no baked towers/attackers/army/hero/HUD; art lane agrees with simulation guide.
Negative clause: no labels, changed viewpoint/river direction/moved crossing, blocked clearings/doors, dense unplayable terrain or mutable objects. Keep actual prompt/reference input within verified token reservation.

OUTPUT / REVIEW / HANDOFF
Save raw request/response/native original,usage/finish reason/provider association into versioned high-res staging outside Git; never overwrite1K/current runtime or rejected versions. Manifest records actual pixels/decode/SHA256, source/prompt/guide hashes, usage/budget liabilities and honest technical/spatial/visual status. Compare normalized/logical geometry with guide tolerance, native detail and intended small screen: camera/light/period/biome/clearings/margins/river/lane/pads/no baked objects. DecodePASS is not spatial/visualPASS. Record FAIL/RECOVERABLE/UNVERIFIED without new calls. Supply comparison sheets and per-ID deferrals/failures. Code AI owns derivatives/runtime integration; no automatic current selection or owner approval.

FIRST PHASE
The appended ordered32 IDs and queue are the complete phase. Maximum32 first output attempts, no automatic replacements. Reuse/defer items explicitly; continue unrelated ready selected IDs without filler. Stop and report after ready IDs finish or defer. Do not start2K merely because first32 are terminal.

LATER2K — PLANNED73, NOT ACTIVATED NOW
Owner requested later divided groups. Proposed A32 hero paintings,B17 mounts/rigs/rivals,C24 army listed below. Owner activates/schedules a later group after4K report; no repeated per-ID permission once activated. Use native2K,candidateCount1 and fresh bounded reservations with same lock/quota/no-retry rules. One parts/rig sheet counts one image, not multiple paid calls. Follow frozen identities and ready pose/parts/contact guides. Use transparency for isolated subjects when supported; otherwise an explicit matte contract, never checkerboard painted as transparency.
A32: ancient Knight is knight-mounted-master, not invented portrait-ancient-knight; seven other ancient classes and eight each medieval/powder/mech. Stable face/class/kit/full-body/contact envelope, no HUD/stat labels/invented gear.
B17: three mounts,eight rig sheets,six rival appearance slots. Generated names do not rename frozen game rivals.
C24: three army roles through eight ages; corrected batch17 attacker-AGE-heavy can be reviewed army references, never confused with five siege roles.
Other375 baseline IDs stay1K. Content failures outside105 selected upgrades do not authorize extra generation.

DELIVER
First32 report: reused/attempted/technical pass/visual fail/deferred per ID, source/guide/output hashes, native dimensions, actual usage/commitments/invoiceUNKNOWN, preserved provenance, live lock reconciliation and quota/ambiguity blockers. Later73 group proposal remains pending scheduling. No provider claims without records; no runtime/owner acceptance from terminal status. Update current handoff/budget evidence without discarding history. No Git staging/push/deletion here; assets remain outside Git with restore provenance.
'''

q = json.loads((PLAN/'INTERACTIVE-HIGH-RES-QUEUE-2026-10-03.json').read_text())
for group in dict.fromkeys(x['group'] for x in q['items']):
    items = [x for x in q['items'] if x['group'] == group]
    image += '\n' + group + ' — ' + str(len(items)) + ' SELECTED IDS\n'
    image += '\n'.join(f"{x['order']:02d}. {x['id']}" for x in items) + '\n'

(PLAN/'REPLACEMENT-CODE-AI-PROMPT-2026-10-03.txt').write_text(code, encoding='utf-8')
(PLAN/'INTERACTIVE-IMAGE-AI-PROMPT-2026-10-03.txt').write_text(image, encoding='utf-8')
print(json.dumps({'codeCharacters':len(code),'imageCharacters':len(image),'queue':len(q['items'])}))
