"""Planner documentation only: preserve old prompts and create complete successors."""
from pathlib import Path
import re
ROOT=Path(__file__).resolve().parents[2]
PLAN=ROOT/'docs/plan'
AUDIT='BOTH-AI-LATEST-RECHECK-2026-10-05.md'
CODE='CODE-AI-NEXT-AFTER-V8-RECHECK-2026-10-05.txt'
IMAGE='IMAGE-AI-NEXT-AFTER-V8-RECHECK-2026-10-05.txt'
def step(text,n,new):
    before,body=text.split('4. Step-by-Step Instructions',1)
    instructions,after=body.split('5. Edge Cases & Failure Modes',1)
    pattern=rf'(?m)^{n}\. .*?$'
    instructions,count=re.subn(pattern,f'{n}. {new}',instructions)
    assert count==1,(n,count)
    return before+'4. Step-by-Step Instructions'+instructions+'5. Edge Cases & Failure Modes'+after
code=(PLAN/'CODE-AI-WHOLE-GAME-EXECUTION-PROMPT-2026-10-05.txt').read_text(encoding='utf-8-sig')
code=code.replace('BOTH-AI-WHOLE-SCOPE-AUDIT-2026-10-05.md',AUDIT).replace('qa/planner-verification-20261005','qa/planner-recheck-20261005').replace('output/playwright/planner-verification-20261005','output/playwright/planner-recheck-20261005').replace('IMAGE-DELIVERY-INTERFACE-V7-2026-10-05.json','IMAGE-DELIVERY-INTERFACE-V8-2026-10-05.json')
code=step(code,6,'Repair Retreat modal isolation. Independent current keyboard probe: open Retreat, focus Cancel, Tab twice reaches background move:1,4; Enter changes rebornActions count8 to9 while the aria-modal dialog is open. Use the existing modal lifecycle with proper focus containment, background inertness, action guards and focus restoration; preserve Escape/cancel/no-spend and confirmed once-only settlement.')
code=step(code,7,'Verify the modal using real forward/backward Tab, Enter/Space, Escape, pointer/touch, screen navigation, resize and stale-target gestures. Background panel/dock/navigation must neither act nor steal focus while open; both campaign and practice consequences remain isolated. Save before/after state and exactly-one confirm evidence.')
code=step(code,8,'Retain the verified redraw-safe delegated Tactical map activation. Fresh planner probes pass held pointer across550ms of redraw, ordinary/reduced motion, touch, keyboard alternative, resize and closed cells. Add only missing invalidation/cancel/double-gesture coverage justified by changes; do not repeat the old handler repair or rewrite working legal rules.')
code=step(code,9,'Retain the verified Forge decision inside the panel beside confirmation at825x375,933x424,1180x820,1280x720. Current injected Flint Club fixture shows atk3 to4; that is a layout fixture. Verify compare/cancel/confirm and actual derived stats for all six naturally obtained or legally crafted slots; keep injected acquisition separate.')
code=step(code,10,'Retain the verified14CSSpx Tactical name/count/health/action overlay. Inspect all other Hero/Forge/Army/Defense/Story/support labels and all interactive targets at intended screen sizes; several Forge slot captions still scale inside the SVG. Provide accessible48CSSpx action alternatives and useful focus/announcements without changing legal geometry merely to enlarge labels.')
code=step(code,11,'Retain the verified removal of Kingdom development provenance from player guidance. Review every support screen for useful complete text and meaningful empty/error/loading states; keep art limitations in QA/handoffs.')
code=step(code,26,'Audit individual v8 rows against actual consumer use. Nine static rows are ready (eight newly rebound plus pre-existing Iron heavy); four bounded joints and Healer boot are pieces, never full rigs. V8 preservedLimits says Gunpowder heavy, Future ranged and Future heavy have64px acceptance, while current plate-catalog sets staticMaxHeight130 for all three. Measure their actual calls; enforce the supported visible-height scope or record exact missing larger-size acceptance. Do not silently extend64px to130px or edit Image outputs.')
code=step(code,30,'Continue ordinary isolated fresh-save play through all remaining ready workflows. Fresh planner reproduction built four sites, waited for production, recruited, manually won guard10,5, equipped earned orb loot-160-0-accessory, returned, deployed hero/army, naturally lost Siege after2cleared waves, applied one SETTLE_DEFENSE and reloaded. Now prepare a naturally funded Workshop/splash defense and record a win or exact failure, with pre-result, once-only settlement, survivors, reload and defeat recovery. Continue six-slot/skills/Market/Story/five-War/support/save flows and earned age progression; label fixtures and auto assistance.')
code=step(code,35,'Verify final examined source/dist/native-www/APK closure, ZIP CRC, previewID/min24/target36/compile36 and zero uses-permission. Fresh existing package92f47e7ed32f5b654a4aeafb3dc760698577e47ebbbc39594a5aaa3e3dbd76d0,359122611bytes,275files passes; do not build solely to repeat that result. Build after your actual source/consumer changes, record warnings and final hashes, and keep deviceSTOPPED.')
code=step(code,36,'Create versioned optimized runtime textures for measured display sizes where package/texture cost warrants them. Current241PNGs occupy358048634bytes; many2048canvases display near130px. Use existing local tools, preserve originals/derivatives/alpha/contact/UV semantics, compare actual display pixels and record catalog/source-output hashes plus package savings. Measure browser costs; do not claim unmeasured Android60fps or reduce acceptance thresholds.')
code=code.replace('Fresh baseline suite is96tests,94PASS/2ENOENT,exit1','Fresh baseline suite is99tests,97PASS/2ENOENT,exit1')
code=code.replace('The map-click/retreat/Forge-layout failures are separate confirmed application behavior.','The old map-click/immediate-retreat/Forge-layout/readability defects are repaired. Current Retreat modal background keyboard activation is a separate confirmed application defect; one first harness total-count failure was corrected using action offsets and was not a duplicate-settlement bug.')
code=code.replace('but repair visibility and prove natural acquisition separately.','and retain the repaired visibility. Earned orb acquisition/equip/reload passes independently; remaining slot coverage is separate.')
code=code.replace('Do not force v7 partial parts','Do not force v8 partial parts')
code=code.replace('ran the 96-test suite','ran the fresh 99-test suite').replace('do not report96PASS','do not report99PASS')
code=code.replace('browser-audit.mjs','browser-recheck.mjs').replace('{kingdom,tactical,forge-compare}.png','{kingdom-825x375,tactical-825x375,forge-825x375}.png')
code=code.replace('final browser report errors=[] does not imply gameplay acceptance.', 'fresh browser report has one failed modal-isolation check; its other19checks pass, with no page exceptions recorded.')
code=code.replace('Current evidence:', 'Current baseline: 19 fresh browser checks PASS and1FAIL for modal isolation;172 image/evidence hash associations checked,170present match/decode and2known missing historical guides;12joint-overlap reproductions match. Natural Siege defeat/settlement now verified; prepared natural win remains open. Read IMAGE-LOCAL-DELIVERY-V8-HANDOFF-2026-10-05.md, qa/image-local-delivery-v8-20261005/checkpoint.json, scenes.json and class-semantics-v8.json. Current evidence:')
# Replace the historical blanket statement with the fresh defect while retaining bounded harness context.
code=code.replace('[ ] Retreat cancel preserves state; confirm resolves/settles only once with documented consequences.','[ ] Retreat traps focus, makes every background control inert, restores focus, preserves cancel/Escape state and resolves/settles only once on confirm.')
code=code.replace('[ ] Final web/native package matches final examined source;', '[ ] Versioned runtime texture optimization has measured visual/preservation/cost evidence where feasible; final web/native package matches final examined source;')
(PLAN/CODE).write_text(code,encoding='utf-8')
image=(PLAN/'IMAGE-AI-WHOLE-LOCAL-EXECUTION-PROMPT-2026-10-05.txt').read_text(encoding='utf-8-sig')
image=image.replace('BOTH-AI-WHOLE-SCOPE-AUDIT-2026-10-05.md',AUDIT)
image=image.replace('Latest executor-reported versions: Python3.13.7, Pillow12.3.0, NumPy2.5.3, OpenCV5.0.0, SciPy1.18.1; verify locally, do not present these as freshly measured.', 'Current planner-measured versions: Python3.13.7, Pillow12.3.0, NumPy2.5.3, OpenCV5.0.0, SciPy1.18.1 at C:/Python313/python.exe; recheck your execution runtime before processing.')
image=image.replace('Current Image inputs:', 'Current Image inputs: docs/plan/IMAGE-DELIVERY-INTERFACE-V8-2026-10-05.json; docs/plan/IMAGE-LOCAL-DELIVERY-V8-HANDOFF-2026-10-05.md; qa/image-local-delivery-v8-20261005/{checkpoint.json,class-semantics-v8.json,scenes.json,arithmetic-regression.json,arithmetic-scene-diff.json,assemblies,terrain}; scripts/image_v8_local_delivery.py and image_v8_withdraw_ridge_roads.py as inspected helpers. These supersede v7 status where stated. Prior supporting inputs:')
image=image.replace('Outputs: new versioned derivatives','Fresh planner evidence: qa/planner-recheck-20261005/{v8-verification.json,v8-bindings.json,artifact-summary.json,survey-arithmetic-report.json}; Python3.13.7/Pillow12.3.0/NumPy2.5.3/OpenCV5.0.0/SciPy1.18.1 independently measured. 170present hash/decode associations match and2known guide paths are absent;12overlap metrics reproduce at -25/0/+25. Binding metrics are not whole-body or geography acceptance.\n\nOutputs: new versioned derivatives')
image=step(image,4,'Reuse14v8ready rows unchanged: nine static troops, Ranger sleeve-to-open-hand, Healer boot, Healer leg/greave and greave/boot, Paladin knee/greave. Preserve exact semantic/size/angle limits. Independent12overlap calculations reproduce. SourceBinding gates on all14rows still sayUNVERIFIED despite binding summary; publish truthful evidence-backed gate states in a new successor, never rewrite v8.')
image=step(image,7,'Use v8\'s78semantic crop records and eight missing-chain diagrams as inventory evidence. Validate each anatomy label against native pixels and distinguish delivered-part missing, unmeasured attachment, inseparable ROI and source anatomy absent. Do not repeat generic component inventory or promote a strip of separate pieces as a neutral body.')
image=step(image,8,'Start with a bounded Healer head ROI from the existing native2048sheet: top-left quadrant visibly has six painted heads and separate braids. V8 diagram missing head means not delivered; native heads are present. Inspect front/three-quarter compatible views, preserve face/neck/hair, use source-region foreground masks and at most one justified correction per genuinely new method. Then work on feasible Healer torso/skirt/arm/leg source regions and other classes\' independent ROIs. Do not invent unseen anatomy or destructive global chroma-key.')
image=step(image,12,'Deliver a compatible source-backed neutral assembly or precise missing-link diagram for each of eight classes. V8 diagrams contain disconnected uniformly resized tiles and NOT_A_SINGLE_SCALE_BODY, not full anatomy. Determine real attachment landmarks/camera/scale for present parts; publish valid subchains when whole-body completion is impossible. Continue independent classes/ROIs rather than treating one generic source inventory as exhaustion.')
image=step(image,13,'Publish explicit consumable transforms for ready and newly feasible joints: canvas dimensions with width/height named, derivative-local parent/child landmarks, source-to-crop transform, parent matrix, child neutral matrix, rotation center/order/sign and draw order. V8 canvas arrays actually store[height,width] (Ranger[1139,760]); do not leave Code to assume[w,h]. Ranger parent canvas pivot[380,569], child[385.6,535.4] has measured insertion; distinguish these two anchors and the rigid rotation rule. Reproduce the existing12metrics without a new placement search; unknown side remainsUNKNOWN.')
image=step(image,19,'Retain the corrected int16 blue arithmetic and synthetic overflow case. Fresh independent32source check reproduces8changed masks/13360pixels before component filtering. V7 helper still contains historical unsigned arithmetic; prevent future work from accidentally using the obsolete survey path, without rerunning or rewriting historical production/evidence. Add only missing regression coverage justified by a new helper change; candidate masks never prove banks.')
image=step(image,20,'Use direct native pixel inspection to trace actual painted roads, river channel/both banks, deck/approach polygons, walkable ground, rock/obstacle polygons and baked mutable content for all32scene IDs. V8 rejected relative-luminance/Sobel road methods after three scene inspections;31roads remain untraced. Use a genuinely different source-supported per-scene annotation method (manual polygon/path tracing is allowed), one baseline and at most one justified correction per method. Do not repeat Sobel threshold sweeps or claim all independent per-scene methods exhausted.')
image=step(image,21,'Regenerate new-version diagnostics from the final current annotations. Existing v8 Adventure overlay and all32contact sheet still contain withdrawn magenta ridge traces although current JSON road arrays are empty. Keep v8 evidence as historical rejected-method evidence; new overlays must agree exactly with current annotation/status/legend and source/contract hashes. Do not mix rejected candidates with claimed painted paths.')
image=step(image,22,'Measure full legal sites/corridors/contact/height envelopes against independently traced features. V8 Stone mean73.76legalpx is a coarse-track residual with40px uncertainty, not physical registration PASS. Current white deck polygon is visibly below painted wood, and ring line crosses or hugs rock edges. Manual uncertainty must be too small to distinguish safe corridors from obstacles before promotion; trace actual deck/banks, not a brown stripe or centroid contour.')
image=step(image,24,'Prepare coordinated versioned proposals when source-backed registration needs change. V8\'s four-viewport sheet merely resizes a full scene to[viewportWidth/2,viewportHeight/2], distorting aspect at multiple sizes and omitting runtime HUD/panels/camera. Produce actual uniform camera-fit/crop comparisons using frozen viewport chrome/safe areas plus sparse/mature footprints and picking implications. Keep affine[60,-10,25,35,170,165]/Hall0.1312active unchanged; any proposal needing coordinated review staysPROPOSED.')
image=step(image,27,'Publish a successor v9-or-newer interface without overwriting v4-v8, final source/derivative/diagram/mask/recipe/annotation/overlay hashes, named coordinate conventions, exact readySubset, semantic/size/pose limits, truthful gate states and failed/partial blockers. Retain64px limits for horse/motor/future transport, Gunpowder heavy/Future ranged/Future heavy unless independently inspected larger-size evidence genuinely supports expansion. Report that Code currently advertises130px for those three troops; Code owns consumer repair, Image owns delivery evidence.')
image=step(image,29,'Refresh the full Image per-ID queue with source-backed finite methods and concrete next actions. Preserve completed/exhausted attempts and failed bytes-unavailable records. Terrain generic exhaustion is not exhaustion of manual per-source geography; available Healer heads are not absent source anatomy. Update handoff pointers without overwriting concurrent Code history. Continue all independently feasible actors/rigs/scenes/buildings/sites/UI/mount metadata before stopping.')
image=image.replace('successor JSON interface','successor v9-or-newer JSON interface').replace('Never overwrite v4-v7','Never overwrite v4-v8')
image=image.replace('[ ] All32scenes have actual painted geography annotations', '[ ] New diagnostic overlays agree with final annotations and explicitly exclude withdrawn traces; four-viewport evidence uses uniform runtime camera/chrome rather than stretched source thumbnails.\n[ ] All32scenes have actual painted geography annotations')
image=image.replace('v7interface omits some transform fields present in measurements; expose them in consumable coordinates so Code does not guess.', 'v8 adds useful pivots/cuffs but still lacks explicit width/height and complete local matrices; expose them so Code does not guess.')
(PLAN/IMAGE).write_text(image,encoding='utf-8')
for name in [CODE,IMAGE]:
    text=(PLAN/name).read_text()
    headings=re.findall(r'(?m)^([1-7])\. (Task Summary|Environment|Inputs & Outputs|Step-by-Step Instructions|Edge Cases & Failure Modes|Acceptance Criteria|Do NOT)$',text)
    assert len(headings)==7,(name,headings)
print(CODE,IMAGE)
