import json,pathlib,hashlib,re,html,collections
R=pathlib.Path(__file__).resolve().parents[2];Q=R/'qa/planner-final-images-20261007'
def read(p):return json.loads((R/p).read_text(encoding='utf-8-sig'))
def save(p,v):(Q/p).write_text(json.dumps(v,indent=2),encoding='utf-8')
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
checks=read('qa/planner-final-images-20261007/delivery-checks.json');metrics={x['id']:x for x in read('qa/planner-final-images-20261007/pixel-metrics.json')};rows=[]
green={'armory-stone','barracks-stone','farm-bronze','workshop-iron','townhall-industrial','mine-industrial','hall-industrial','adventure-site-town'}
new4={'troop-stone-melee','troop-stone-ranged','troop-industrial-ranged','troop-industrial-heavy'}
sheets={'troop-medieval-ranged','troop-gunpowder-heavy','troop-future-ranged','creature-drone'}
cards={'hero-mount-horse','hero-mount-motor-transport','hero-mount-future-transport','knight-mounted-master','troop-bronze-heavy','troop-medieval-heavy','troop-medieval-melee','troop-future-heavy'}
for who,pre in [('environment','ENVIRONMENT-ART'),('actors','ACTORS-EQUIPMENT')]:
 d=read(f'docs/plan/{pre}-RESIDUAL-INTERFACE-2026-10-07.json');by={x['id']:x for x in checks['producers'][who]['rowsAudit']}
 for r in d['rows']:
  a=by[r['id']];m=metrics.get(r['id']);decision='CANDIDATE_REQUIRES_CONSUMER_VALIDATION';pixel='UNVERIFIED';reason=['Binding/dimensions passed; overview review does not certify every native edge or runtime placement.']
  if r['status'] in ('FAIL','PARTIAL'):decision='RETAIN_'+r['status'];reason=list(r['limitations'])
  if r['id'] in green:decision='HOLD_GENERAL_WORLD_PLACEMENT';pixel='FAIL';reason=['Visible flat green base material remains; distinguish source base from foliage/despill and preserve structure before consumer repair.']
  if r['id'] in new4:decision='HOLD_BROKEN_DERIVATIVE';pixel='FAIL';reason=['Independent source/output pixels show near-empty subject; current native source is a candidate for source-supported Code consumer preparation. Historical original hash mismatch and crop affine omission are explicit.']
  elif who=='actors' and (r['id'].startswith('attacker-') or r['id'].startswith('creature-')):
   decision='HOLD_GENERAL_SPRITE';pixel='FAIL';reason=['Visible chroma edge/floor or baked scenery/sheet; color metrics alone do not establish this verdict. Review native pixels and preserve real purple effects.']
  if r['id'] in ('gear-stone-helm','gear-stone-boots'):decision='HOLD_DIRTY_CARD_OR_SPRITE';pixel='FAIL';reason=['Large visible magenta background survives extraction.']
  if r['id']=='troop-iron-melee':decision='HOLD_DAMAGED_SUBJECT';pixel='FAIL';reason=['Monochrome damaged silhouette is not a complete painted Legionary.']
  if r['id'] in sheets:decision='SHEET_REQUIRES_FRAME_SELECTION';pixel='FAIL';reason=['Whole multi-pose/prop/text/background sheet cannot be drawn as one live unit; explicitly source-bound ROIs are required.']
  if r['id'] in cards:decision='STATIC_CARD_ONLY_UNTIL_EXTRACTION';reason=['Declared static identity may be shown within bounded card use; background/whole-pose art does not establish transparent map sprite or articulated gait.']
  if r['id'].startswith('effect-'):decision='ATLAS_INPUT_REQUIRES_FRAME_ROIS';reason=['Separate frames/UVs/effect meanings must be selected; full sheet is not one active effect.']
  if r['id'].startswith('healer-head-') and r['status']=='READY':decision='BOUNDED_STATIC_HEAD_CARD';pixel='PASS';reason=['Overview/native crop supports static face-card use only; no full body/neck attachment promotion.']
  if r['id']=='healer-boot':decision='RETAIN_BOUNDED_PART';pixel='PASS';reason=['135x131 boot hash preserved; bounded part, not complete limb/body.']
  if not r.get('output'):decision='METADATA_ONLY_'+r['status'];reason.append('No output URL; full reproducible transform/side/arc proof required before any joint use.')
  if r['id']=='healer-leg-subchain':decision='DIAGNOSTIC_SUBCHAIN_TRANSFORMS_UNVERIFIED';reason.append('Per-part identity matrices/900x900 parent canvas do not reproduce warps/independent trims; no complete body or continuous gait.')
  if r['id']=='skill-offense':pixel='PASS';decision='BOUNDED_SQUARE_MATERIAL';reason=['Visible magenta background removed; delivered square plaque is not the reported circular badge.']
  rows.append({'id':r['id'],'producer':who.upper(),'producerStatus':r['status'],'binding':'PASS','dimension':'PASS' if r.get('output') else 'NOT_APPLICABLE','pixel':pixel,'metadata':'PARTIAL' if a['metadataProblems'] else 'UNVERIFIED','metadataFindings':a['metadataProblems'],'missingEvidence':a['missingEvidence'],'decision':decision,'maxDisplayCssPx':r.get('maxDisplayCssPx'),'source':r.get('source'),'output':r.get('output'),'sourceToOutput':r.get('sourceToOutput'),'reason':reason,'metrics':m,'runtime':'UNVERIFIED','owner':'UNVERIFIED','nextAction':'Validate or minimally prepare isolated Code consumer input; otherwise retain precise blocker and continue independent game work.'})
 for s in d.get('supportRows',[]):rows.append({'id':s['id'],'producer':'ENVIRONMENT','binding':'PASS','pixel':'FAIL','decision':'REFERENCE_ONLY_FULL_MOCK_SCREENSHOT','sourceBinding':'UNVERIFIED','output':s,'reason':['Baked mock controls/text/actors/device frame; no clean environmental layer.'],'runtime':'UNVERIFIED','owner':'UNVERIFIED','nextAction':'Author a real live support-screen composition from adequate clean material/native UI.'})
for s in checks['scenes']:
 failures=[x for x in s['independentRoadChecks'] if not x['pass']]
 rows.append({'id':s['id'],'producer':'ENVIRONMENT','binding':'PASS','dimension':'PASS','pixel':'PARTIAL','spatial':'FAIL' if failures else 'UNVERIFIED','decision':'PARTIAL_UNPROMOTED_PROPOSAL_ONLY','roadConflicts':failures,'source':s['source'],'proposal':s['proposal'],'runtime':'UNVERIFIED','owner':'UNVERIFIED','nextAction':'Validate source-specific actual roads/banks/decks/obstacles/contacts and camera; do not activate unresolved geometry.'})
for cls in ['knight','ranger','warlock','mage','paladin','barbarian','necromancer','healer']:rows.append({'id':'hero-'+cls+'-complete-body-and-gait','producer':'COVERAGE','status':'BLOCKED','decision':'NO_COMPLETE_BODY_DELIVERED','evidencePaths':['qa/image-residual-executor-20261007/actors/assemblies/'+cls+'-chain.png'],'reason':['Existing delivered class chain is a missing-link diagnostic. Complete compatible anatomy/socket/frame evidence is unavailable.'],'nextAction':'Finish class-specific UI/rules and bounded card presentation; keep complete-body/gait acceptance separate.'})
save('per-id-status.json',{'date':'2026-10-07','status':'INCOMPLETE','rows':rows,'note':'Candidate sets are not readySubset blanket approval; metrics are diagnostics.'})
families={
'OWN-01':'section/owner acceptance','OWN-02':'fresh independent repository','OWN-03':'asset reuse/consumption','OWN-04':'connected campaign','OWN-05':'approved composition','OWN-06':'realistic appearance','OWN-07':'Day1 sites','OWN-08':'all eight ages','OWN-09':'terrain/sites','OWN-10':'mount gait','OWN-11':'eight classes/kits','OWN-12':'Defense roles','OWN-13':'Tactical','OWN-14':'era identity','OWN-15':'return quality','OWN-16':'complete handoff','OWN-17':'installed environment','OWN-18':'paid authority','OWN-19':'offline/no publishing',
'SYS-01':'economy','SYS-02':'Army/creatures','SYS-03':'six equipment slots','SYS-04':'Forge/Market','SYS-05':'Hero/skills/spells','SYS-06':'Adventure','SYS-07':'Tactical input/modals','SYS-08':'Defense','SYS-09':'Story/objectives','SYS-10':'support/audio','SYS-11':'tutorial','SYS-12':'recoverable saves','SYS-12a':'save boundaries','SYS-13':'shared progression','SYS-14':'native package','SYS-15':'mobile/performance','SYS-16':'five War flows','GIT-01':'durable copy/restore/Git'}
req=[]
for id,subject in families.items():
 status='PARTIAL';fresh=True;scope='Fresh current source/tests and bounded browser evidence; ordinary full workflow not certified.';nextaction='Complete corresponding whole-scope Code prompt steps and publish actual state/runtime evidence.'
 if id in ['OWN-05','OWN-06','OWN-10','OWN-11','OWN-14','SYS-07']:status='FAIL'
 if id in ['OWN-01','OWN-18','SYS-14','GIT-01']:status='UNVERIFIED';fresh=False;scope='Owner acceptance/paid authority/device/package/storage not freshly verified by this planner.'
 if id in ['OWN-02','OWN-16','OWN-17']:status='PASS';scope='Bounded repository/source baseline, new complete prompt artifacts or freshly measured interpreter versions only.'
 req.append({'id':id,'subject':subject,'status':status,'scope':scope,'fresh':fresh,'coreTests':'98/100 PASS; 2 exact historical guide ENOENT; test coverage is not whole workflow acceptance','nextAction':nextaction,'owner':'UNVERIFIED','device':'STOPPED','evidencePaths':['qa/planner-final-images-20261007/node-tests.txt','qa/planner-final-images-20261007/browser-report.json','qa/planner-final-images-20261007/per-id-status.json']})
save('requirements-status.json',{'date':'2026-10-07','status':'INCOMPLETE','rows':req,'scope':'Complete canonical requirement crosswalk with explicitly bounded fresh/historical acceptance, not assertion of full player testing.'})
snap=read('qa/planner-final-images-20261007/input-hashes.json')
save('integration-contract.json',{'schema':1,'date':'2026-10-07','status':'INCOMPLETE','interfaceHashes':{p:snap[p] for p in snap if p.endswith('RESIDUAL-INTERFACE-2026-10-07.json')},'decisions':'qa/planner-final-images-20261007/per-id-status.json','frozenAffine':[60,-10,25,35,170,165],'frozenHallScale':0.1312,'geometryActivation':'PROPOSED_ONLY','paidAuthority':'UNVERIFIED_SEPARATE_OWNER_AUTHORIZATION; NO_NEW_PAID_CALLS_FOR_CODE','producerCounts':{k:{'rows':v['rows'],'statuses':v['statuses'],'phantomReady':v['phantomReady'],'unlistedReady':v['unlistedReady']} for k,v in checks['producers'].items()},'consumerBindings':{'src/data/plate-catalog.json':'actor.js/drawPlate and all role lookups','src/data/age-buildings.json':'main.js/kingdom','src/data/reviewed-source-selection.json':'main.js/kingdom background selection','src/data/stone-scene.json':'main.js/kingdom Hall placement','src/data/mode-scenes.json':'main.js/paintModeGround/adventure/tactical/defense','src/data/actor-atlas.json':'actor.js/rig.js','src/data/anatomy-binding-v1.json':'anatomy.js','src/data/static-mounts-v1.json':'actor.js static mounts','src/data/portrait-cards.json':'portraits.js','scripts/build.mjs':'complete new consumer catalog/texture asset closure'},'codeTextureNamespace':'assets/runtime-code-20261007/','rowsReadyForGeneralRuntime':'NONE_BLANKET_APPROVED; use per-row bounded decisions and fresh consumer verification','capPolicy':'maxDisplayCssPx after uniform camera/DOM scale and visible alpha extent; conservative lower established height/longest limit while ambiguous','newFourRejectedOutputs':sorted(new4),'originalPreservationMismatches':[r for r in checks['preservation'] if r.get('hashMatch') is False],'device':'STOPPED','owner':'UNVERIFIED'})
# Every mandatory reading-order document is indexed without overwriting it.
docs=['AGENTS.md','START-HERE.md','CURRENT-STATUS.md','DECISIONS.md','docs/SESSION-HANDOFF.md','docs/BUILD-PROGRESS.md','docs/plan/README.md']
docs+=['docs/plan/'+x for x in ['INSTALLED-ENVIRONMENT.md','AUDIT-UPDATE.md','MASTER-PLAN.md','REQUIREMENTS-TRACEABILITY.md','VISUAL-DESIGN.md','MOCK-FIDELITY-AUDIT.md','ART-REUSE.md','asset-manifest.json','reviewed-art-ledger.json','raw-inventory.json','public-art-inventory.json','GAME-DATA-REFERENCE.json','INSTALLATION-TRANSFER.md','REVIEW-AND-STATUS.md','NEXT-AI-PROMPT.md','FULL-IMPLEMENTATION-SPEC.md','DATA-ADOPTION-LEDGER.json','SOURCE-EQUATIONS-ADDENDUM-2026-10-03.md','WHOLE-PLAN-INDEPENDENT-AUDIT-2026-10-04.md','THREE-AI-OWNERSHIP-2026-10-06.md']]
index=[]
for rel in docs:
 p=R/rel
 if p.exists():
  text=p.read_text(encoding='utf-8-sig');index.append({'path':rel,'sha256':sha(p),'bytes':p.stat().st_size,'headings':re.findall(r'^#{1,4} .+$',text,re.M)})
 else:index.append({'path':rel,'missing':True})
save('reading-index.json',index)
# Actual artifacts only; CSS uses contain rather than stretching diagnostic comparisons.
sections=[]
for p in sorted(Q.glob('*.jpg')):sections.append(f'<article><h2>{html.escape(p.name)}</h2><a href="{p.name}"><img loading="lazy" src="{p.name}"></a></article>')
for p in sorted((Q/'pixels').glob('*.png')):sections.append(f'<article><h2>{html.escape(p.name)}</h2><a href="pixels/{p.name}"><img loading="lazy" src="pixels/{p.name}"></a></article>')
(Q/'gallery.html').write_text('<!doctype html><html lang="en"><meta charset="utf-8"><title>Both image deliveries — independent audit 7 October</title><style>body{background:#181a1d;color:#eee;font:16px system-ui;margin:24px}img{display:block;max-width:100%;height:auto}article{margin:30px 0;padding:16px;border:1px solid #77643b}a{color:#e2c580}</style><h1>Independent image + runtime audit — INCOMPLETE</h1><p>JavaScript ES modules/HTML/CSS/SVG; Node24.19.0. Producer READY labels in sheets are claims, not acceptance. Natural browser startup/Skirmish and accelerated Army age fixtures are separate. Native overview sheets do not certify every edge; source/output diagnostics identify explicit failures. No product or image output was edited.</p><p><a href="../../docs/plan/BOTH-RESIDUAL-IMAGE-DELIVERIES-INDEPENDENT-AUDIT-2026-10-07.md">Audit</a> · <a href="../../docs/plan/CODE-AI-WHOLE-GAME-AFTER-BOTH-IMAGE-AUDIT-2026-10-07.txt">Complete Code prompt</a> · <a href="per-id-status.json">Per-ID decisions</a></p>'+''.join(sections),encoding='utf-8')
save('summary.json',{'status':'INCOMPLETE','node':'24.19.0','tests':{'total':100,'passed':98,'failed':2,'failureScope':'exact v4/v5 guide ENOENT'},'artifactCounts':{'environment':145,'supportReferenceOnly':9,'actors':167,'actorOutputs':156,'scenesPartial':32},'readySetsReconciled':True,'sevenDimensionRepairs':True,'fullClassBodiesReady':0,'sourcePreservationMismatchIds':sorted(new4),'newFourDerivativeMatte':'FAIL','authorization':'UNVERIFIED_LOCAL_RECORD_CONFLICT','browser':'22 captures; bounded ordinary startup/Skirmish and8age Army fixtures; focus restoration FAIL, effective SVG inertness incomplete, guarded tested map command PASS','package':'historical only; no build/device this turn','productionEdits':False,'executorDispatch':False})
print('WROTE',len(rows),'per-ID rows and',len(req),'canonical requirement rows; input files',len(snap))
print('INTERFACE HASHES',json.dumps(read('qa/planner-final-images-20261007/integration-contract.json')['interfaceHashes']))
print('READING MISSING',[r['path'] for r in index if r.get('missing')])
